fix BUG Overlay.of(context)  return null
Fix this bug
```dart
AchievementView(
    navigatorKey.currentState.context, // global navigator key
  // other options...
);
/* 
Throw NoSuchMethodError: The method 'insert' was called on null.
because Overlay.of(context)  return null
*/
``` 
with this option all is good
```dart
AchievementView(
    navigatorKey.currentState.context, // global navigator key
    overlay: navigatorKey.currentState.overlay,
  // other options...
);

```